### ISSUE TITLE
Redit Error for Windows Fix [Suggestion]

### ISSUE THREAD

**Issue by tootyta** [TunnelBlanket/Houdini#5]
So when running Houdini on Python Windows 2.7, I had gotten Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it. python windows. This occured when trying to login to the server, to fix this I just installed the latest build from here https://github.com/MicrosoftArchive/redis/releases and the error completely fixed itself.

**Comment by Alothappens** [comment]
@tootyta I experienced this issue as soon as he made this source code public, and it is in fact, due to it not being compatible with windows, there is however, a version that has ported to windows (the one you linked) but it was already addressed when I pointed it out to Basil and it's already noted on the "read me" (http://prntscr.com/hcysxx), so this issue was completely unnecessary and you would not have had to do this if you bothered to read it in the first place...

**Comment by tootyta** [comment]
No need to get so salty lmao, I was in a rush to install this and was just trying to help out people, sorry lmao.

**Comment by Alothappens** [comment]
It is included, again, learn to read.

**Comment by tootyta** [comment]
Again, I said, "included in the installation though...", LMAO http://prntscr.com/hcz64d . You don't seem to know what I'm talking about.

**Comment by Alothappens** [comment]
http://prntscr.com/hcysxx Literally says it right there... You seriously can't even scroll down like a couple more inches...

**Comment by tootyta** [comment]
Again, you, "seriously" don't understand what I'm talking about. I usually pay attention to the Installation section, and I basically said it should be added there so people who are just trying to install it understand. I don't understand why you tend to get so pissed by the fact that when I mean installation, I literally mean the section labled, "installation" lmao. Not the entire article, use your context for once.

**Comment by Alothappens** [comment]
"Prerequisites" literally means something that is required to be done for something else to happen, not to mention this section appears above the installation process and putting this message in installation is completely pointless as it has nothing to do with it, this section simply states you can run a command to install all the modules at once, which will not work with the required version of Redis for the Windows OS.

**Comment by tootyta** [comment]
Sigh.. you still don't seem to be getting what I'm trying to say lmao. I'll just end this here since you can't understand the uttermost simplest of things.

**Comment by Alothappens** [comment]
I understand you perfectly, but you don't need to include in installation when it was already stated in another section. This repetition is getting boring... give it up already.

**Comment by trix80** [comment]
Who wanna hoop tmrw 4:00 pm sharp

**Comment by tootyta** [comment]
@trix80 lolololol 
@Alothappens I'm just giving my suggestion, sheesh. You don't need to backstab me about my suggestion, worry about your own stuff. I'm sorry, jeez.

**Comment by Alothappens** [comment]
You could have avoided this utterly pointless discussion if you had just read the damn read me file. But aight
