### ISSUE TITLE
Server Bars?

### ISSUE THREAD

**Issue by tootyta** [TunnelBlanket/Houdini#7]
Not much of a bug, but are server bars ever going to be implemented?

**Comment by ketnipz** [comment]
Server bars should already be working for you in Houdini. They are calculated based on the number of players on the server and the maximum player capacity set in your `houdini.conf`.

If they aren't working for you please let me know ASAP.

**Comment by tootyta** [comment]
https://prnt.sc/i582vi They don't seem to be working for me, the server bars look off due to customization of the client. However, they seem to work with other sources such as KitSune AS2. The server bars keep freaking out and flashing on 1 - 2 - 3 - 4 - 5 - FULL bars. http://prntscr.com/i583ys

**Comment by tootyta** [comment]
I managed to fix this issue, however not much testing has been completed on this, "fix" so I'm not sure if it would be ready-to-go to be added to the source. The file I edited is Houdini-master\Houdini\Handlers\Login, Login.py. After the else selection statement, else:
                serverPopulation = 1 . I added if serverPopulation is 0:
                    serverPopulation = 1 . http://prntscr.com/i6635x . The reasoning behind this is that the math going on in Houdini, because the outcome of that math will usually be 0 if there are little players on the server. When the server sends the serverPopulation as 0 to the client, it freaks out. So this check basically prevents that I guess.
